### ISSUE TITLE
Добавить варианты сортировки во вкладку разблокированных

### ISSUE THREAD

**Issue by Kibnet** [Kibnet/Unlimotion#60]
Добавить комбобокс с выбором сортировки в прямой и обратной последовательности:
1. По дате разблокировки
2. По дате создания
3. По дате изменения
4. По дате планируемого начала выполнения
5. По дате планируемого окончания выполнения
6. По длительности
7. По приоритету

**Comment by Kozlov-AE** [comment]
https://github.com/Kibnet/Unlimotion/pull/91

**Comment by Kozlov-AE** [comment]
По дате изменения не сделал, т.к. view model не содержит данного поля. Решили сделать отдельным таском

**Comment by Kozlov-AE** [comment]
https://github.com/Kibnet/Unlimotion/pull/91
