### ISSUE TITLE
Watcher для отслеживания изменения файлов

### ISSUE THREAD

**Issue by Kibnet** [Kibnet/Unlimotion#9]
Мониторить папку с задачами.
При изменении любого файла, подгружать из него обновлённые данные в память и обновлять во всех представлениях.

**Comment by Kozlov-AE** [comment]
Наверное стоит начать отсюда https://learn.microsoft.com/ru-ru/dotnet/api/system.io.filesystemwatcher?view=net-7.0

**Comment by Kibnet** [comment]
https://github.com/Kibnet/Unlimotion/pull/99
